server:
  port: 8905
spring:
  application:
    name: config-security-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fuzhengjunopen/springcloud-config.git
          username: fuzhengjunopen
          password: fuzhengjun#123321#open
          clone-on-start: true #开启启动时直接从git获取配置
  security: #配置用户名和密码
    user:
      name: fuzhengjun
      password: 123456